### ISSUE TITLE
Passing array as parameter in mailable

### ISSUE THREAD

**Issue by bop10** [JoggApp/laravel-mail-viewer#16]
Hello, i have a mailable with an array parameter in the constructor (it's a string array), and i need to pass it in my mailviewer config so i can preview my email.

I tried something like this:
`  
MailTemplate::class => [
            'Example title', 'Example subtitle',
            [
               'Example text3', 'Example text 2'
            ],
            '#43A047'
 ]`

Which causes the following error:
`Undefined index: states`

How can i pass the array correctly?

Thanks

**Comment by introwit** [comment]
@bop10 thank you for pointing it out Sergio, fixed the issue and have tagged a [new release](https://github.com/JoggApp/laravel-mail-viewer/releases/tag/v3.1.0) 🙂 Lemme know how it goes ❤️

**Comment by bop10** [comment]
Works! Thanks a lot for the fast response! @introwit
