### ISSUE TITLE
Route in Mailable

### ISSUE THREAD

**Issue by OzanKurt** [JoggApp/laravel-mail-viewer#20]
@component('mail::button', ['url' => route('activate', ['token' => $token])])

This doesn't work.

**Comment by OzanKurt** [comment]
![image](https://user-images.githubusercontent.com/8682003/55170599-e2dbc800-5187-11e9-829c-b05b1d5c3310.png)

What exactly is working at the moment, you should make a list so that we can test the working parts.

**Comment by introwit** [comment]
This is not our package. Sorry, but wrong repository :slightly_smiling_face:

**Comment by OzanKurt** [comment]
Omg! Amazing! Thanks! I am so glad that I am wrong.
