### ISSUE TITLE
Databasetransactions are not reverted

### ISSUE THREAD

**Issue by paddypaddo** [JoggApp/laravel-mail-viewer#24]
While viewing the mail in the browser, the database is used for some variabels in the mail.
Everything needed to view the mail stays in our database, even after closing down the mail.

In the find method of the mailviewer.php, the mailable is returned at line 68, but the rollback is done at line 71.
The database rollback is never done, if a mailable is returned. 

What we think is the solution is to render the mail, then rollback the transaction and returning the mail.

**Comment by introwit** [comment]
sorry I missed this issue earlier somehow. Why would we want to rollback the transaction though?  We need that data to be persisted so that we can use them in the view. Feel free to re-open the issue if you feel something is missing.
