### ISSUE TITLE
Object not found in my browser when I open an email

### ISSUE THREAD

**Issue by guilherme90** [JoggApp/laravel-mail-viewer#25]
When I added my emails to mailables and try to access from the URL, it returned that

<a href="https://ibb.co/JQPNxYK"><img src="https://i.ibb.co/JQPNxYK/error-2.png" alt="error-2" border="0"></a>

My mails list
<a href="https://ibb.co/0sjY3TM"><img src="https://i.ibb.co/0sjY3TM/error-1.png" alt="error-1" border="0"></a>

**Comment by introwit** [comment]
If you followed the install instructions step by step, it will work properly. There might be something you have missed. If you still face the problem, re-open the issue :)

**Comment by guilherme90** [comment]
It is very easy to close the problem right after I open it so there are no open problems in the repository.

Do not do this, if I am creating a problem, there is certainly a problem and I am asking for your support help.
