### ISSUE TITLE
Target class [Illuminate\Database\Eloquent\Factory] does not exist.

### ISSUE THREAD

**Issue by SergioGMB** [JoggApp/laravel-mail-viewer#28]
Hello. I have fresh LV8 project. When trying to use the package on any mail i get the following error:

```
Illuminate\Contracts\Container\BindingResolutionException
Target class [Illuminate\Database\Eloquent\Factory] does not exist.
```

Following https://github.com/barryvdh/laravel-ide-helper/issues/1047#issuecomment-689484210 , i think this is the same problem.

The bug is in MailViewer.php, in this use i think:
`use Illuminate\Database\Eloquent\Factory as EloquentFactory;`

**Comment by davejamesmiller** [comment]
Same here. Installing the `laravel/legacy-factories` package fixed it for me, as a temporary workaround.

**Comment by introwit** [comment]
Hi, This package has been archived and will no longer be maintained/updated. The reason being Laravel now itself provides a really convenient way to [preview mailables in the browser](https://laravel.com/docs/8.x/mail#rendering-mailables). Have updated the readme to indicate this.
