### ISSUE TITLE
PHP 8.0 support?

### ISSUE THREAD

**Issue by charlesteh** [JoggApp/laravel-mail-viewer#29]
would like to know if this package is available for PHP8.0? thanks!

**Comment by introwit** [comment]
Hi, This package has been archived and will no longer be maintained/updated. The reason being Laravel now itself provides a really convenient way to [preview mailables in the browser](https://laravel.com/docs/8.x/mail#rendering-mailables). Have updated the readme to indicate this and will be archiving this repo soon as well.
